export const PNG_ICONS = [
  { path: '/icons/001-rootkit.png', name: 'Rootkit' },
  { path: '/icons/002-hacker.png', name: 'Hacker' },
  { path: '/icons/003-hacker-1.png', name: 'Hacker 1' },
  { path: '/icons/004-cyber-criminal.png', name: 'Cyber Criminal' },
  { path: '/icons/005-cyber-criminal-1.png', name: 'Cyber Criminal 1' },
  { path: '/icons/006-hacker-2.png', name: 'Hacker 2' },
  { path: '/icons/007-hack.png', name: 'Hack' },
  { path: '/icons/008-hacker-3.png', name: 'Hacker 3' },
  { path: '/icons/009-cyber-attack.png', name: 'Cyber Attack' },
  { path: '/icons/010-malware.png', name: 'Malware' },
  { path: '/icons/011-cartoon.png', name: 'Cartoon' },
  { path: '/icons/012-hacker-4.png', name: 'Hacker 4' },
  { path: '/icons/013-hacker-5.png', name: 'Hacker 5' },
  { path: '/icons/014-incognito.png', name: 'Incognito' },
  { path: '/icons/015-account.png', name: 'Account' },
  { path: '/icons/016-cyber-attack-1.png', name: 'Cyber Attack 1' },
  { path: '/icons/017-cyber-crime.png', name: 'Cyber Crime' },
  { path: '/icons/018-hacker-6.png', name: 'Hacker 6' },
  { path: '/icons/019-hacker-7.png', name: 'Hacker 7' },
  { path: '/icons/020-hacker-8.png', name: 'Hacker 8' },
  { path: '/icons/021-spyware.png', name: 'Spyware' },
  { path: '/icons/022-hacker-9.png', name: 'Hacker 9' },
  { path: '/icons/023-rootkit-1.png', name: 'Rootkit 1' },
  { path: '/icons/024-hacker-10.png', name: 'Hacker 10' },
  { path: '/icons/025-cyber-attack-2.png', name: 'Cyber Attack 2' },
  { path: '/icons/026-hacker-11.png', name: 'Hacker 11' },
  { path: '/icons/027-hacker-12.png', name: 'Hacker 12' },
  { path: '/icons/028-hacker-13.png', name: 'Hacker 13' },
  { path: '/icons/029-skull.png', name: 'Skull' },
  { path: '/icons/030-cyber-crime-1.png', name: 'Cyber Crime 1' },
  { path: '/icons/031-hacker-14.png', name: 'Hacker 14' },
  { path: '/icons/032-hacker-15.png', name: 'Hacker 15' },
  { path: '/icons/033-hacker-16.png', name: 'Hacker 16' },
  { path: '/icons/034-hacker-17.png', name: 'Hacker 17' },
  { path: '/icons/035-hacker-18.png', name: 'Hacker 18' },
  { path: '/icons/036-skull-1.png', name: 'Skull 1' },
  { path: '/icons/037-cyber-attack-3.png', name: 'Cyber Attack 3' },
  { path: '/icons/038-hacker-19.png', name: 'Hacker 19' },
  { path: '/icons/039-hacker-20.png', name: 'Hacker 20' },
  { path: '/icons/040-hacker-21.png', name: 'Hacker 21' },
  { path: '/icons/041-hacker-22.png', name: 'Hacker 22' },
  { path: '/icons/042-hacker-23.png', name: 'Hacker 23' },
  { path: '/icons/043-hacker-activity.png', name: 'Hacker Activity' },
  { path: '/icons/044-hacker-24.png', name: 'Hacker 24' },
  { path: '/icons/045-virus.png', name: 'Virus' },
  { path: '/icons/046-cybercrime.png', name: 'Cybercrime' },
  { path: '/icons/047-hacker-25.png', name: 'Hacker 25' },
  { path: '/icons/048-hacker-26.png', name: 'Hacker 26' },
  { path: '/icons/049-hacker-27.png', name: 'Hacker 27' },
  { path: '/icons/050-hacker-28.png', name: 'Hacker 28' },
  { path: '/icons/051-hacker-29.png', name: 'Hacker 29' },
  { path: '/icons/052-account-1.png', name: 'Account 1' },
  { path: '/icons/053-virus-1.png', name: 'Virus 1' },
  { path: '/icons/054-hacker-30.png', name: 'Hacker 30' },
  { path: '/icons/055-hacker-31.png', name: 'Hacker 31' },
  { path: '/icons/056-malware-1.png', name: 'Malware 1' },
  { path: '/icons/057-malware-2.png', name: 'Malware 2' },
  { path: '/icons/058-cyber-attack-4.png', name: 'Cyber Attack 4' },
  { path: '/icons/059-hacker-32.png', name: 'Hacker 32' },
  { path: '/icons/060-hacker-33.png', name: 'Hacker 33' },
  { path: '/icons/061-hack-1.png', name: 'Hack 1' },
  { path: '/icons/062-malware-3.png', name: 'Malware 3' },
  { path: '/icons/063-terminal.png', name: 'Terminal' },
  { path: '/icons/064-skull-2.png', name: 'Skull 2' },
  { path: '/icons/065-hack-2.png', name: 'Hack 2' },
  { path: '/icons/066-hacker-34.png', name: 'Hacker 34' },
  { path: '/icons/067-hacker-35.png', name: 'Hacker 35' },
  { path: '/icons/068-botnet.png', name: 'Botnet' },
  { path: '/icons/069-white-hat.png', name: 'White Hat' },
  { path: '/icons/070-botnet-1.png', name: 'Botnet 1' },
  { path: '/icons/071-hacker-36.png', name: 'Hacker 36' },
  { path: '/icons/072-cyber-eye.png', name: 'Cyber Eye' },
  { path: '/icons/073-hacking.png', name: 'Hacking' },
  { path: '/icons/074-hacker-37.png', name: 'Hacker 37' },
  { path: '/icons/075-hacking-1.png', name: 'Hacking 1' },
  { path: '/icons/076-email.png', name: 'Email' },
  { path: '/icons/077-phishing.png', name: 'Phishing' },
  { path: '/icons/078-binary-code.png', name: 'Binary Code' },
  { path: '/icons/079-hacker-38.png', name: 'Hacker 38' },
  { path: '/icons/080-binary-code-1.png', name: 'Binary Code 1' },
  { path: '/icons/081-skull-3.png', name: 'Skull 3' },
  { path: '/icons/082-hacking-2.png', name: 'Hacking 2' },
  { path: '/icons/083-hacker-39.png', name: 'Hacker 39' },
  { path: '/icons/084-cyber-criminal-2.png', name: 'Cyber Criminal 2' },
  { path: '/icons/085-botnet-2.png', name: 'Botnet 2' },
  { path: '/icons/086-encryption.png', name: 'Encryption' },
  { path: '/icons/087-botnet-3.png', name: 'Botnet 3' },
  { path: '/icons/088-cyber-attack-5.png', name: 'Cyber Attack 5' },
  { path: '/icons/089-hacking-3.png', name: 'Hacking 3' },
  { path: '/icons/090-malicious.png', name: 'Malicious' },
  { path: '/icons/091-flash-drive.png', name: 'Flash Drive' },
  { path: '/icons/092-cyber-crime-2.png', name: 'Cyber Crime 2' },
  { path: '/icons/093-hacker-40.png', name: 'Hacker 40' },
  { path: '/icons/094-hacker-41.png', name: 'Hacker 41' },
  { path: '/icons/095-hacker-42.png', name: 'Hacker 42' },
  { path: '/icons/096-hacker-43.png', name: 'Hacker 43' },
  { path: '/icons/097-hacker-44.png', name: 'Hacker 44' },
  { path: '/icons/098-hacker-45.png', name: 'Hacker 45' },
  { path: '/icons/099-cyber-attack-6.png', name: 'Cyber Attack 6' },
  { path: '/icons/100-malicious-1.png', name: 'Malicious 1' },
  { path: '/icons/101-malware-4.png', name: 'Malware 4' },
  { path: '/icons/102-hacking-4.png', name: 'Hacking 4' },
  { path: '/icons/103-hacker-46.png', name: 'Hacker 46' },
  { path: '/icons/104-hacker-47.png', name: 'Hacker 47' },
  { path: '/icons/105-cybercrime-1.png', name: 'Cybercrime 1' },
  { path: '/icons/106-hacker-48.png', name: 'Hacker 48' },
  { path: '/icons/107-security.png', name: 'Security' },
  { path: '/icons/108-cybercrime-2.png', name: 'Cybercrime 2' },
  { path: '/icons/109-malware-5.png', name: 'Malware 5' },
  { path: '/icons/110-hack-3.png', name: 'Hack 3' },
  { path: '/icons/111-hacker-49.png', name: 'Hacker 49' },
  { path: '/icons/112-warning.png', name: 'Warning' },
  { path: '/icons/113-black.png', name: 'Black' },
  { path: '/icons/114-cyber-attack-7.png', name: 'Cyber Attack 7' },
  { path: '/icons/115-cyber-eye-1.png', name: 'Cyber Eye 1' },
  { path: '/icons/116-hacker-50.png', name: 'Hacker 50' },
  { path: '/icons/117-cyber-attack-8.png', name: 'Cyber Attack 8' },
  { path: '/icons/118-anonymous.png', name: 'Anonymous' },
  { path: '/icons/119-hacker-51.png', name: 'Hacker 51' },
  { path: '/icons/120-hacker-52.png', name: 'Hacker 52' },
  { path: '/icons/121-botnet-4.png', name: 'Botnet 4' },
  { path: '/icons/122-hacker-53.png', name: 'Hacker 53' },
  { path: '/icons/123-face.png', name: 'Face' },
  { path: '/icons/124-hacker-54.png', name: 'Hacker 54' },
  { path: '/icons/125-growth-hacking.png', name: 'Growth Hacking' },
  { path: '/icons/126-hacker-research.png', name: 'Hacker Research' },
  { path: '/icons/127-cybersecurity.png', name: 'Cybersecurity' },
  { path: '/icons/128-hacker-55.png', name: 'Hacker 55' },
  { path: '/icons/129-hacker-56.png', name: 'Hacker 56' },
  { path: '/icons/130-black-hat.png', name: 'Black Hat' },
  { path: '/icons/131-usb-drive.png', name: 'USB Drive' },
  { path: '/icons/132-hacker-57.png', name: 'Hacker 57' },
  { path: '/icons/133-finger-print.png', name: 'Finger Print' },
  { path: '/icons/134-virus-2.png', name: 'Virus 2' },
  { path: '/icons/135-vpn.png', name: 'VPN' },
  { path: '/icons/136-spyware-1.png', name: 'Spyware 1' },
  { path: '/icons/137-spyware-2.png', name: 'Spyware 2' },
  { path: '/icons/138-security-threat.png', name: 'Security Threat' },
  { path: '/icons/139-website-hacker.png', name: 'Website Hacker' },
  { path: '/icons/140-attack.png', name: 'Attack' },
  { path: '/icons/141-ddos.png', name: 'DDoS' },
  { path: '/icons/142-cyber.png', name: 'Cyber' },
  { path: '/icons/143-cyber-attack-9.png', name: 'Cyber Attack 9' },
  { path: '/icons/144-smartphone.png', name: 'Smartphone' },
  { path: '/icons/145-usb.png', name: 'USB' },
  { path: '/icons/146-email-1.png', name: 'Email 1' },
  { path: '/icons/147-cpu.png', name: 'CPU' },
  { path: '/icons/148-credit-card.png', name: 'Credit Card' },
  { path: '/icons/149-vpn-1.png', name: 'VPN 1' },
  { path: '/icons/150-online-robbery.png', name: 'Online Robbery' },
  { path: '/icons/151-computer.png', name: 'Computer' },
  { path: '/icons/152-virus-3.png', name: 'Virus 3' },
  { path: '/icons/153-error.png', name: 'Error' },
  { path: '/icons/154-cyber-attack-10.png', name: 'Cyber Attack 10' },
  { path: '/icons/155-phishing-1.png', name: 'Phishing 1' },
  { path: '/icons/156-computer-1.png', name: 'Computer 1' },
  { path: '/icons/157-hacker-58.png', name: 'Hacker 58' },
  { path: '/icons/158-hack-4.png', name: 'Hack 4' },
  { path: '/icons/159-face-id.png', name: 'Face ID' },
  { path: '/icons/160-malware-6.png', name: 'Malware 6' },
  { path: '/icons/161-stalking.png', name: 'Stalking' },
  { path: '/icons/162-hat.png', name: 'Hat' },
  { path: '/icons/163-hacker-59.png', name: 'Hacker 59' },
  { path: '/icons/164-malware-7.png', name: 'Malware 7' },
  { path: '/icons/165-malware-8.png', name: 'Malware 8' },
  { path: '/icons/166-bot.png', name: 'Bot' },
  { path: '/icons/167-cyber-security.png', name: 'Cyber Security' },
  { path: '/icons/168-banner.png', name: 'Banner' },
  { path: '/icons/169-encryption-1.png', name: 'Encryption 1' },
  { path: '/icons/170-hacker-60.png', name: 'Hacker 60' },
  { path: '/icons/171-firewall.png', name: 'Firewall' },
  { path: '/icons/172-password.png', name: 'Password' },
  { path: '/icons/173-worm.png', name: 'Worm' },
  { path: '/icons/174-unsecure.png', name: 'Unsecure' },
  { path: '/icons/175-malware-9.png', name: 'Malware 9' },
  { path: '/icons/176-unsecured-shield.png', name: 'Unsecured Shield' },
  { path: '/icons/177-hacker-61.png', name: 'Hacker 61' },
  { path: '/icons/178-anonymous-1.png', name: 'Anonymous 1' },
  { path: '/icons/179-hacker-62.png', name: 'Hacker 62' },
  { path: '/icons/180-hacker-63.png', name: 'Hacker 63' },
  { path: '/icons/181-hacker-64.png', name: 'Hacker 64' },
  { path: '/icons/182-hacker-65.png', name: 'Hacker 65' },
  { path: '/icons/183-robot-assistant.png', name: 'Robot Assistant' },
  { path: '/icons/184-botnet-5.png', name: 'Botnet 5' },
  { path: '/icons/185-file.png', name: 'File' },
  { path: '/icons/186-warning-1.png', name: 'Warning 1' },
  { path: '/icons/187-keylogger.png', name: 'Keylogger' },
  { path: '/icons/188-credit-card-1.png', name: 'Credit Card 1' },
  { path: '/icons/189-laptop.png', name: 'Laptop' },
  { path: '/icons/190-hack-5.png', name: 'Hack 5' },
  { path: '/icons/191-broken-shield.png', name: 'Broken Shield' },
]

export function getRandomIcon(emojis, pngIcons = PNG_ICONS) {
  const all = [...emojis, ...pngIcons.map(i => i.path)]
  return all[Math.floor(Math.random() * all.length)]
}
